### ISSUE TITLE
Page not formatting & escape characters in URLs

### ISSUE THREAD

**Issue by domfennell** [cuttlefishers/opendata#11]
Hi @RoastVeg,

The data is looking great! We're just encountering a couple of issues:

- The first page of your feed is not formatting for us; and
- It looks like there are escape characters being included in URLs, including the `"next"` URL at the bottom - `https:\/\/www.sportsuite.co.uk\/api\/cs-api\/openactive?afterTimestamp=1561027028&afterId=391980`.

Could you take a look, please?

Thanks,

Dom

**Comment by RoastVeg** [comment]
Hi @domfennell 
I have fixed the latter issue, has the former also been fixed as a side effect?

**Comment by domfennell** [comment]
Hi @RoastVeg, thanks for taking a look at this. I can see that the second issue (escape characters) has been addressed, however, the first page of the feed still isn't formatting for us...

**Comment by domfennell** [comment]
Hi @RoastVeg, any luck with fixing the formatting issue on [the first page](https://www.sportsuite.co.uk/api/cs-api/openactive) of your feed?

**Comment by RoastVeg** [comment]
Hi @domfennell I am unable to replicate the issue - the page formats perfectly well for me. Can you elaborate?

**Comment by domfennell** [comment]
Hi @thill-odi, can you please take a look at https://www.sportsuite.co.uk/api/cs-api/openactive and see it if works for you? Thanks.

**Comment by jonferguson** [comment]
Any further issues with this, seems to format for me correctly?

**Comment by domfennell** [comment]
Working for me now. 👍
